CREATE SCHEMA IF NOT EXISTS BIBLIOTECA;

USE BIBLIOTECA;

DROP TABLE IF EXISTS PRESTITO;
DROP TABLE IF EXISTS SCRITTO;
DROP TABLE IF EXISTS AUTORE;
DROP TABLE IF EXISTS LIBRO;
DROP TABLE IF EXISTS SUCCURSALE;
DROP TABLE IF EXISTS STUDENTE;

CREATE TABLE SUCCURSALE (
	nome VARCHAR(255) NOT NULL,
	citta VARCHAR(63) NOT NULL,
	cap CHAR(5) NOT NULL,
	via VARCHAR(255) NOT NULL,
	nCivico VARCHAR(31) NOT NULL,
	PRIMARY KEY (nome)
);

CREATE TABLE LIBRO (
	id INTEGER NOT NULL,
	isbn CHAR(13) NOT NULL,
	titolo VARCHAR(255) NOT NULL,
	annoPubblicazione INTEGER NOT NULL,
	lingua VARCHAR(63) NOT NULL,
	copie INTEGER NOT NULL,
	succursale VARCHAR(255) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (succursale) REFERENCES SUCCURSALE(nome),
	UNIQUE (isbn)
);

CREATE TABLE AUTORE (
	id INTEGER NOT NULL,
	nome VARCHAR(255) NOT NULL,
	cognome VARCHAR(255) NOT NULL,
	dataNascita DATE NOT NULL,
	luogoNascita VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE SCRITTO (
	autore INTEGER NOT NULL,
	libro INTEGER NOT NULL,
	PRIMARY KEY (autore, libro),
	FOREIGN KEY (autore) REFERENCES AUTORE(id),
	FOREIGN KEY (libro) REFERENCES LIBRO(id)
);

CREATE TABLE STUDENTE (
	matricola INTEGER NOT NULL,
	nome VARCHAR(255) NOT NULL,
	cognome VARCHAR(255) NOT NULL,
	citta VARCHAR(63) NOT NULL,
	cap CHAR(5) NOT NULL,
	via VARCHAR(255) NOT NULL,
	nCivico VARCHAR(31) NOT NULL,
	telefono VARCHAR(15) NOT NULL,
	PRIMARY KEY (matricola)
);

CREATE TABLE PRESTITO (
	id INTEGER NOT NULL,
	dataPrestito DATE NOT NULL,
	dataRestituzione DATE,
	studente INTEGER NOT NULL,
	libro INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (studente) REFERENCES STUDENTE(matricola),
	FOREIGN KEY (libro) REFERENCES LIBRO(id)
);
